<a href="https://colab.research.google.com/github/UTSAVsarkar/BASICS_OF_TENSORFLOW/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.18.0


In [3]:
scalar = tf.constant(7)

In [4]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim

0

In [6]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
another_matrix = tf.constant([
    [1., 2., 3.],
    [10., 20., 30.],
    [11., 12., 13.]
], dtype=tf.float16)

In [12]:
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 1.,  2.,  3.],
       [10., 20., 30.],
       [11., 12., 13.]], dtype=float16)>

In [14]:
tensor = tf.constant(
    [
      [
        [1, 2, 3],
        [4, 5, 6]
      ],
      [
       [7, 8, 9],
       [10, 11, 12]
      ]
    ]
)

In [15]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [16]:
tensor.ndim

3